version: "3.9"
services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_DB: "finance"
      POSTGRES_USER: "finance-user"
      POSTGRES_PASSWORD: "finance-pass"
    ports:
      - "5432:5432"

  tgbot:
    volumes:
      - ./config:/config
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    depends_on:
      - pg
    links:
      - pg
